export const SEARCH_POKEMON_REQUEST = "SEARCH_POKEMON_REQUEST";
export const SEARCH_POKEMON_SUCCESS = "SEARCH_POKEMON_SUCCESS";
export const SEARCH_POKEMON_ERROR = "SEARCH_POKEMON_ERROR";

export const LOAD_POKEMON_LIST_REQUEST = "LOAD_POKEMON_LIST_REQUEST";
export const LOAD_POKEMON_LIST_SUCCESS = "LOAD_POKEMON_LIST_SUCCESS";
export const LOAD_POKEMON_LIST_ERROR = "LOAD_POKEMON_LIST_ERROR";

export const CLEAR_POKEMON_LIST = "CLEAR_POKEMON_LIST";

export const SEARCH_AND_CAPTURE_POKEMON_REQUEST = "SEARCH_AND_CAPTURE_REQUEST";
export const SEARCH_AND_CAPTURE_ERROR = "SEARCH_AND_CAPTURE_ERROR";
