export const LOAD_MORE_POKEMON_DETAILS = "LOAD_MORE_POKEMON_DETAILS";

export const GET_EVOLUTION_CHAIN_REQUEST = "GET_EVOLUTION_CHAIN_REQUEST";
export const GET_EVOLUTION_CHAIN_SUCCESS = "GET_EVOLUTION_CHAIN_SUCCESS";
export const GET_EVOLUTION_CHAIN_ERROR = "GET_EVOLUTION_CHAIN_ERROR";
